version: '3.9'

services:
  nuxt:
    build: .
    container_name: d2
    restart: always
    networks: 
      - pn
    environment:
      NODE_ENV: production   
    ports:
      - 80:8080
    command: 
      "npm run serve"
networks:
  pn:
    external: 
      name: private-network